name = "go-shortener"
main = "src/index.ts"
compatibility_date = "2026-06-12"
workers_dev = false
preview_urls = false

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADjGLLK2kLzklZSk"
TURNSTILE_HOSTNAMES = "go.snkisk.com"

[secrets]
required = ["TURNSTILE_SECRET", "ACCESS_TEAM_DOMAIN", "ACCESS_ADMIN_AUDS"]

[[triggers.crons]]
cron = "0 3 * * *"

[[d1_databases]]
binding = "DB"
database_name = "go_shortener"
database_id = "4ba0bc48-b5f8-4d19-ba4d-23e02339d04b"
